---
- name: Install chezmoi via snap
  community.general.snap:
    name:
      - chezmoi
    classic: yes
  when: chezmoi_install_method == "snap"

- name: Install chezmoi using a package
  ansible.builtin.import_tasks: download-chezmoi.yml
  when: chezmoi_install_method != "snap"

- name: Initialize chezmoi (empty)
  ansible.builtin.command: "chezmoi init"
  when: not chezmoi_init_url

- name: Initialize chezmoi
  ansible.builtin.command: "chezmoi init --apply --verbose {{ chezmoi_init_url }}"
  when: chezmoi_init_url
  changed_when: false
