---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-chezmoi"
      ansible.builtin.include_role:
        name: "ansible-role-chezmoi"
      vars:
        chezmoi_init_url: "https://github.com/hussainweb/ansible-test-chezmoi"
        chezmoi_version: "2.31.0"
