---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-centos
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: instance-debian
    image: docker.io/pycontribs/debian:latest
    pre_build_image: true
  - name: instance-ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
