---
- name: Prepare
  hosts: all
  tasks:
    - name: Install packages (debian)
      ansible.builtin.apt:
        pkg:
          - curl
          - git
          - gpg
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: Install packages (redhat)
      ansible.builtin.yum:
        name:
          - curl
          - git
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "RedHat"
