---
- name: Prepare
  hosts: all
  tasks:
    - name: Install packages (debian)
      apt:
        pkg:
          - git
          - curl
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: Install packages (redhat)
      yum:
        name:
          - git
          - curl
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "RedHat"
