---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Run chezmoi
    command: "chezmoi --version"
    register: chezmoi_version_output
    changed_when: false

  - name: Assert that chezmoi ran without error
    assert:
      that:
        - "chezmoi_version_output.rc == 0"
        - "'chezmoi' in chezmoi_version_output.stdout"
